### ISSUE TITLE
Unable to zef install Data::Importers

### ISSUE THREAD

**Issue by morgantomj** [antononcube/Raku-Data-Slurps#1] opened 2024-10-17 03:09 UTC
I tried to use 'zef install Data::Importers' - here is what I get:
dad@gpa:~/raku/Photo$ uname -a 
Linux gpa 6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
dad@gpa:~/raku/Photo$ zef install Data::Importers
===> Searching for: Data::Importers
===> Updating fez mirror: http://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updated fez mirror: http://360.zef.pm/
===> Searching for missing dependencies: JSON::Fast:ver<0.19+>, URI:ver<0.3.7+>:auth<zef:raku-community-modules>
===> Failed to find dependencies: JSON::Fast:ver<0.19+>
Failed to resolve some missing dependencies (use e.g. --exclude="JSON::Fast" to skip)
dad@gpa:~/raku/Photo$ zef install JSON::Fast
All candidates are currently installed
No reason to proceed. Use --force-install to continue anyway
dad@gpa:~/raku/Photo$ zef install URI
All candidates are currently installed
No reason to proceed. Use --force-install to continue anyway

#############
Running Ubuntu 24.04.1 LTS

I have used zef to install multiple raku modules without any real problems.

**Comment by antononcube** [comment] 2024-10-17 07:53
Thank you for your interest in "Data::Importers" and reporting this issue!

It looks like on your system you cannot install "JSON::Fast" -- that is a basic or fundamental package.

Are you able to install "JSON::Fast" by separately, by itself?

After you reported this issue I added GitHub Actions scripts -- both macos and linux install without problems.

**Comment by morgantomj** [comment] 2024-10-17 12:41
I'm not sure why the formatting crossed out some text in my answer ... But JSON::Fast is already installed:
zef install JSON::Fast
All candidates are currently installed
No reason to proceed. Use --force-install to continue anyway

URI is also already installed.

Tom

**Comment by morgantomj** [comment] 2024-10-17 12:49
Here is my version of JSON::Fast 
zef info JSON::Fast
- Info for: JSON::Fast
- Identity: JSON::Fast:ver<0.17>:auth<cpan:TIMOTIMO>
- Recommended By: Zef::Repository::Ecosystems<cpan>
- Installed: Yes
Description:	 A naive, fast json parser and serializer; drop-in replacement for JSON::Tiny
License:	 Artistic-2.0
Source-url:	 http://www.cpan.org/authors/id/T/TI/TIMOTIMO/Perl6/JSON-Fast-0.17.tar.gz
Provides: 1 modules
Support:
#   source:	git://github.com/timo/json_fast.git
Depends: 1 items
#####

Is it possible that you are requiring ver<0.19+> and that prevents the install? I tried to upgrade JSON::Fast to a higher version, but I got the same version shown above.

**Comment by antononcube** [comment] 2024-10-17 13:36
> Identity: JSON::Fast:ver<0.17>:authcpan:TIMOTIMO

The dependency in the package is from "JSON::Fast:ver<0.19+>" -- so, this seems to be the problem.

**Comment by antononcube** [comment] 2024-10-20 00:32
Closing, because the issue is just a dependency package version mismatch. (Of "JSON::Fast".)

**Closed as completed by antononcube** 2024-10-20 00:32 UTC

**Comment by antononcube** [comment] 2024-10-22 17:44
> Is it possible that you are requiring ver<0.19+> and that prevents the install? I tried to upgrade JSON::Fast to a higher version, but I got the same version shown above.

Please, try uninstalling "JSON::Fast" and installing the [latest version](https://raku.land/cpan:TIMOTIMO/JSON::Fast). For example:

```
zef uninstall JSON::Fast
zef install "JSON::Fast:ver<0.19>:auth<cpan:TIMOTIMO>"
```

**Comment by morgantomj** [comment] 2024-10-23 01:36
Just to finish this off, I suspect my 2022 version of 'zef' did not grok the ver:<****> additions to the module names. I upgraded to rakudo-star 2024.09, and I can now install 'Data::Importers' ( and other modules) with no problem. Thanx for your attention to these problems.

**Comment by antononcube** [comment] 2024-10-23 12:56
Good to know -- thanks for the update!
